In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
x = np.linspace(0, 10, 10)

In [3]:
y = np.sin(x)

In [4]:
plt.plot(x,y)

In [5]:
plt.show()

In [6]:
plt.plot(x, y)

In [7]:
plt.xlabel("Time")

In [8]:
plt.ylabel("Some function of time")

In [9]:
plt.title("My cool chart")

In [10]:
plt.show()

## Scatter Plot

In [11]:
x = np.linspace(0, 10, 100)

In [12]:
y = np.sin(x)

In [13]:
plt.plot(x, y)

In [14]:
plt.show()

In [15]:
A = pd.read_csv('data_1d.csv',header=None).as_matrix()

In [16]:
x = A[:,0]

In [17]:
y = A[:,1]

In [18]:
plt.scatter(x, y)

In [19]:
plt.show()

In [20]:
x_line = np.linspace(0, 100, 100)

In [21]:
y_line = 2*x_line + 1

In [22]:
plt.scatter(x, y)

In [23]:
plt.plot(x_line, y_line)

In [24]:
plt.show()

## Histogram

In [25]:
plt.hist(x)

(array([ 10.,   9.,   5.,  13.,  10.,  10.,   8.,  16.,  10.,   9.]),
 array([  3.21124861,  12.88597188,  22.56069515,  32.23541842,
         41.91014169,  51.58486496,  61.25958823,  70.9343115 ,
         80.60903477,  90.28375804,  99.95848131]),
 <a list of 10 Patch objects>)

In [26]:
plt.show()

In [27]:
R = np.random.random(10000)

In [28]:
plt.hist(R)

(array([  995.,   935.,  1054.,   944.,  1019.,  1009.,  1011.,  1033.,
          971.,  1029.]),
 array([  1.47790598e-05,   1.00006705e-01,   1.99998632e-01,
          2.99990558e-01,   3.99982484e-01,   4.99974411e-01,
          5.99966337e-01,   6.99958263e-01,   7.99950190e-01,
          8.99942116e-01,   9.99934042e-01]),
 <a list of 10 Patch objects>)

In [29]:
plt.show()

In [30]:
plt.hist(R, bins=20)

(array([ 477.,  518.,  468.,  467.,  546.,  508.,  463.,  481.,  479.,
         540.,  481.,  528.,  516.,  495.,  511.,  522.,  485.,  486.,
         511.,  518.]),
 array([  1.47790598e-05,   5.00107422e-02,   1.00006705e-01,
          1.50002669e-01,   1.99998632e-01,   2.49994595e-01,
          2.99990558e-01,   3.49986521e-01,   3.99982484e-01,
          4.49978448e-01,   4.99974411e-01,   5.49970374e-01,
          5.99966337e-01,   6.49962300e-01,   6.99958263e-01,
          7.49954227e-01,   7.99950190e-01,   8.49946153e-01,
          8.99942116e-01,   9.49938079e-01,   9.99934042e-01]),
 <a list of 20 Patch objects>)

In [31]:
plt.show()

In [32]:
y_actual = 2*x + 1

In [33]:
residuals = y - y_actual

In [35]:
plt.hist(residuals)

(array([  6.,   7.,  15.,  14.,  12.,  18.,  13.,   7.,   6.,   2.]),
 array([ -9.78834827,  -7.57337797,  -5.35840768,  -3.14343738,
         -0.92846708,   1.28650321,   3.50147351,   5.7164438 ,
          7.9314141 ,  10.14638439,  12.36135469]),
 <a list of 10 Patch objects>)

In [36]:
plt.show()