In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
    print e

1
2
3


In [5]:
for e in A:
    print e

1
2
3


In [7]:
# using append for joining in list
L.append(4)

In [8]:
L

[1, 2, 3, 4]

In [9]:
# using append for joining in np array
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [10]:
# using in list
L = L + [5]

In [11]:
L

[1, 2, 3, 4, 5]

In [12]:
# using in numpy
A = A + [4,5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [13]:
L2 = []

In [14]:
for e in L:
    L2.append(e + e)

In [15]:
L2

[2, 4, 6, 8, 10]

In [17]:
# plus sign for Using vector addition in numpy
# plus sign for Using cancatination in list
# If matrix it can matrix addition
A + A

array([2, 4, 6])

In [18]:
# in array
2*A

array([2, 4, 6])

In [19]:
# in list
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [20]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [26]:
L2 = []

In [27]:
for e in L:
    L2.append(e*e)

In [29]:
L2

[1, 4, 9, 16, 25]

In [30]:
A**2

array([1, 4, 9])

In [31]:
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [32]:
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [33]:
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])