In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
Z = np.zeros(10)

In [5]:
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [6]:
Z = np.zeros((10,10))

In [7]:
Z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [9]:
O = np.ones((10,10))

In [10]:
O

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [11]:
R = np.random.random((10,10))

In [12]:
R

array([[ 0.88458674,  0.38898385,  0.85068819,  0.94082404,  0.29592147,
         0.72051842,  0.75200724,  0.25984376,  0.44693138,  0.67955625],
       [ 0.91277359,  0.42385991,  0.4172267 ,  0.57017154,  0.14819766,
         0.34996568,  0.53616342,  0.50960747,  0.00733803,  0.85369249],
       [ 0.0473709 ,  0.30503726,  0.48059553,  0.91411517,  0.67789429,
         0.57361472,  0.95076878,  0.90462847,  0.19811322,  0.9138098 ],
       [ 0.55619347,  0.83521394,  0.74574431,  0.09544779,  0.11266284,
         0.44525488,  0.32956644,  0.14029809,  0.21583707,  0.74411645],
       [ 0.76587531,  0.42719633,  0.47491399,  0.93677985,  0.80209975,
         0.26903882,  0.08748741,  0.62465173,  0.18683943,  0.77939344],
       [ 0.29594271,  0.54136274,  0.58090436,  0.9395599 ,  0.21551661,
         0.73890208,  0.68491902,  0.54341238,  0.86179506,  0.67247146],
       [ 0.51675868,  0.33345409,  0.23371712,  0.08471329,  0.54654352,
         0.70867733,  0.82730067,  0.2991489 

In [13]:
G = np.random.randn((10,10))

TypeError: an integer is required

In [14]:
#Gausian distribution
G = np.random.randn(10,10)

In [15]:
G

array([[ 2.60368556, -0.37588739, -1.9557184 , -1.8425117 , -0.28349938,
        -0.73734894, -1.06414446, -1.1918787 , -0.25162134, -0.88610695],
       [-1.61341732, -0.37372348, -1.32739044, -0.58839273,  0.03819638,
        -1.52158441,  1.11646128,  1.4828447 , -0.54393983, -0.39827772],
       [ 0.10253334, -0.03714103, -0.596945  , -1.06354716,  1.88755144,
         1.1978568 ,  0.89202838,  0.12734999, -0.1449493 ,  0.89128091],
       [-1.2010137 ,  0.40190629,  0.24480468, -2.09272539,  0.54248592,
        -0.75677182, -0.71069234,  0.22302955,  1.59223415,  0.53671483],
       [ 1.3226341 ,  0.64990273, -1.4100892 ,  2.27363362, -2.77093381,
         0.31340601,  0.10745151,  1.6962594 ,  0.0926125 ,  1.22847823],
       [ 0.27796809,  0.24457355, -1.58460755, -1.15985328,  1.27656554,
        -1.47744195,  0.94746046, -2.24993322,  0.42840261, -0.16720806],
       [ 1.53415471,  0.95784835, -0.94345936,  0.49233674,  0.36616988,
         2.08572572, -0.62185423, -0.59380769

In [16]:
G.mean()

0.0088184819863233507

In [17]:
G.var()

1.1445455882595355