In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4]])

In [3]:
Ainv = np.linalg.inv(A)

In [4]:
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [5]:
Ainv.dot(A)

array([[  1.00000000e+00,   4.44089210e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [6]:
A.dot(Ainv)

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [7]:
np.linalg.det(A)

-2.0000000000000004

In [8]:
np.diag(A)

array([1, 4])

In [9]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [10]:
a = np.array([1,2])

In [11]:
b = np.array([3,4])

In [12]:
np.outer(a, b)

array([[3, 4],
       [6, 8]])

In [13]:
np.inner(a, b)

11

In [14]:
a.dot(b)

11

In [15]:
np.diag(A).sum()

5

In [16]:
np.trace(A)

5

In [17]:
X = np.random.randn(100,3)

In [18]:
cov = np.cov(X)

In [20]:
cov.shape

(100, 100)

In [21]:
cov = np.cov(X.T)

In [22]:
cov 

array([[ 0.96181982, -0.16621467,  0.17633478],
       [-0.16621467,  1.17436407, -0.11211728],
       [ 0.17633478, -0.11211728,  1.09575216]])

In [23]:
np.linalg.eigh(cov)

(array([ 0.82009296,  1.02366042,  1.38818267]),
 array([[ 0.85777034, -0.15161679, -0.49116432],
        [ 0.26259424, -0.69217634,  0.67226199],
        [-0.44189852, -0.70562332, -0.55391464]]))

In [24]:
np.linalg.eig(cov)

(array([ 1.38818267,  0.82009296,  1.02366042]),
 array([[ 0.49116432, -0.85777034,  0.15161679],
        [-0.67226199, -0.26259424,  0.69217634],
        [ 0.55391464,  0.44189852,  0.70562332]]))